# Generated by Django 4.2.3 on 2023-07-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title_header',
            field=models.CharField(default='This is the homepage!', max_length=150, verbose_name='Homepage Title'),
        ),
    ]
