# Generated by Django 4.2.3 on 2023-07-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productdetailpage_registed_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetailpage',
            old_name='registed_users',
            new_name='registered_users',
        ),
    ]
